version: "3.8"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5000:5000
    volumes:
      - ../volumes/octoprint/data:/octoprint
    privileged: true
    group_add:
      - 20
  derek_cam:
    image: node
    container_name: derek_cam
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5050:5050
    working_dir: /app
    volumes:
      - /home/lyall/Servers/Derek-Cam:/app
