version: "3.8"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5000:5000
    volumes:
      - ../../Derek/Upload:/upload
      - ../../Derek/Timelapse:/timelapse
      - ../../Derek/Watched:/watched
      - ../volumes/octoprint/data:/octoprint
      - /dev:/dev
    privileged: true
    group_add:
      - 20
  derek_cam:
    build: /home/lyall/Servers/Derek-Cam
    container_name: derek_cam
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5050:5050
    volumes:
      - /home/lyall/Servers/Derek-Cam:/app
      - /dev:/dev
    privileged: true