version: "3.8"
services:
  http_proxy:
    build: /home/lyall/Servers/http_proxy
    container_name: http_proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/lyall/Servers/http_proxy:/app
