version: "3.8"
services:
  http_proxy:
    image: oven/bun:latest
    container_name: http_proxy
    restart: unless-stopped
    network_mode: host
    working_dir: /app
    command: bun .
    volumes:
      - /home/lyall/Servers/HTTP-Reverse-Proxy:/app
