version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ../volumes/jellyfin/config:/config
      - ../volumes/jellyfin/cache:/cache
      #- jellyfin-config:/config
      #- jellyfin-cache:/cache
      - /media/hdd/media:/media
    restart: 'unless-stopped'
#volumes:
#  jellyfin-config:
#    external: true
#  jellyfin-cache:
#    external: true
