version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8096:8096
    volumes:
      - ../volumes/jellyfin/config:/config
      - ../volumes/jellyfin/cache:/cache
      - /media/hdd/media:/media