version: '3.5'
services:
  jellyfin_vue:
    image: ghcr.io/jellyfin/jellyfin-vue:unstable
    container_name: jellyfin_vue
    ports:
      - 8099:80
    restart: 'unless-stopped'
    environment:
      - DEFAULT_SERVERS=https://jellyfin.lyall.cam
      - DISABLE_SERVER_SELECTION=1 # doesnt seem to do anything?
