version: "3.8"
services:
  jmusicbot:
    build: "/home/lyall/Files/Music Bot"
    container_name: jmusicbot
    network_mode: "bridge"
    restart: "unless-stopped"
    volumes:
      - "/home/lyall/Files/Music Bot:/app"
      - /media/hdd/media/Music:/media
