version: "3.8"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    network_mode: bridge
    privileged: true
    ports:
      - 5000:5000
    volumes:
      - ../volumes/octoprint/data:/octoprint
    group_add:
      - 20