version: "3.8"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5000:5000
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /var/run/docker.sock:/var/run/docker.sock
      - ../volumes/octoprint/data:/octoprint
