version: "3.8"
services:
  TEMPLATE:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5000:5000
    volumes:
      - ../volumes/octoprint/data:/octoprint
