version: "3.8"
services:
  openvpn-server:
    image: openvpn/openvpn-as
    container_name: openvpn-server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 1194:1194/udp
      - 1195:1195
      - 1196:1196
    volumes:
      - ../volumes/openvpn-server/data:/openvpn
