# how can i put these in different compose files
version: "3.8"
services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    restart: "unless-stopped"
    network_mode: "bridge"
    cap_add:
      - net_admin
    ports:
      - 8090:8090 # qBittorrent
      - 8112:8112 # Deluge
      - 6881:6881/udp # Deluge inbound torrent traffic
      - 6881:6881/tcp # Deluge inbound torrent traffic
      - 6887:6887/udp # qBittorrent inbound torrent traffic
      - 6887:6887/tcp # qBittorrent inbound torrent traffic
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 9117:9117 # Jackett
    volumes:
      - ../volumes/vpn/vpn:/vpn
    command: '-f ""'
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: "unless-stopped"
    network_mode: service:vpn
    environment:
      - WEBUI_PORT=8090
      - TORRENTING_PORT=6887
    volumes:
      - ../volumes/qbittorrent/config:/config
      - /media/hdd/media/Torrents:/downloads
      - /media/hdd/media:/media
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    restart: "unless-stopped"
    volumes:
      - ../volumes/deluge/config:/config
      - /media/hdd/media/Torrents:/downloads
      - /media/hdd/media:/media
  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: "unless-stopped"
    network_mode: service:vpn
    volumes:
      - ../volumes/sonarr/config:/config
      - /media/hdd/media:/media
      - /media/hdd/media/Torrents:/downloads
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: "unless-stopped"
    network_mode: service:vpn
    volumes:
      - ../volumes/radarr/config:/config
      - /media/hdd/media:/media
      - /media/hdd/media/Torrents:/downloads
  lidarr:
    image: ghcr.io/hotio/lidarr
    container_name: lidarr
    restart: "unless-stopped"
    network_mode: service:vpn
    volumes:
      - ../volumes/lidarr/config:/config
      - /media/hdd/media:/media
      - /media/hdd/media/Torrents:/downloads
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: "unless-stopped"
    network_mode: service:vpn
    volumes:
      - ../volumes/jackett/config:/config
